dictionary/apps/vocabulary/urls.py
from django.urls import path, include

from . import views

app_name = 'vocabulary'

urlpatterns = [
  path('', views.home, name = 'home'),
  path('add_word', views.add_word, name = 'add_word'),
  path('<int:article_id>/remove_word/', views.remove_word, name = 'remove_word'),
  path('<int:article_id>/update_word/', views.update_word, name = 'update_word'),
  path('memorization', views.memorization, name = 'memorization'),
]

dictionary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
  path('', include('vocabulary.urls')),
  path('admin/', admin.site.urls),
  path('accounts/', include('allauth.urls')),
]

dictionary/apps/vocabulary/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

class Word(models.Model):
  word = models.CharField('word', max_length=200)
  definition = models.CharField('definition', max_length=200)
  author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=5)
  adding_date = models.DateTimeField('date of adding', default=timezone.now)

  def __str__(self):
    return self.word

dictionary/apps/vocabulary/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.urls import reverse
from django.utils import timezone

from .models import Word

def home(request):
  try:
    vocabulary_list = Word.objects.filter(author=request.user).order_by('-adding_date')
    return render(request, 'vocabulary/home.html', {'vocabulary_list':vocabulary_list})
  except:
    return render(request, 'vocabulary/home.html')

def add_word(request):
  word = Word.objects.filter(author=request.user.id)
  word.create(
    word=request.POST['word'],
    definition=request.POST['definition'],
    author=request.user,
    adding_date=timezone.now())
  return HttpResponseRedirect( reverse('vocabulary:home') )

def remove_word(request, article_id):
  word = Word.objects.get(id = article_id)
  word.delete()
  return HttpResponseRedirect( reverse('vocabulary:home') )

def update_word(request, article_id):
  word = Word.objects.get(id = article_id)
  word.word = request.POST['newWord']
  word.definition = request.POST['newDefinition']
  word.save()
  return HttpResponseRedirect( reverse('vocabulary:home') )

def memorization(request):
  return render(request, 'vocabulary/memorization.html')

dictionary/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Dictionary app{% endblock %}</title>

  <!-- Bootstrap CSS -->
  <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
    crossorigin="anonymous"
  >
  
  <!-- favicon -->
  {% include 'vocabulary/favicon.html' %}
</head>

<body class="body">
  {% include 'vocabulary/navigation.html' %} <!-- navigation -->
  <div class="container">
    {% block content %}Loading...{% endblock %} <!-- content -->
  </div>
</body>

</html>

dictionary/templates/vocabulary/addWordForm.html
<form action="{% url 'vocabulary:add_word' %}" method="POST">
  {% csrf_token %}
  <div class="form-row">
    <div class="form-group col-md-6">
      <input
        type="text"
        class="form-control"
        placeholder="word"
        autofocus
        autocomplete="off"
        required
        name="word"
        id="word"
      >
    </div>
    <div class="form-group col-md-6">
      <input
        type="text"
        class="form-control"
        placeholder="definition"
        required
        name="definition"
        autocomplete="off"
        id="definition"
      >
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Add word</button>
</form>

dictionary/templates/vocabulary/favicon.html
{% load static %}

<link rel="apple-touch-icon" sizes="57x57" href="{% static 'vocabulary/images/favicon.png' %}">
<link rel="apple-touch-icon" sizes="60x60" href="{% static 'vocabulary/images/favicon.png' %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'vocabulary/images/favicon.png' %}">
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'vocabulary/images/favicon.png' %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static 'vocabulary/images/favicon.png' %}">
<link rel="apple-touch-icon" sizes="120x120" href="{% static 'vocabulary/images/favicon.png' %}">
<link rel="apple-touch-icon" sizes="144x144" href="{% static 'vocabulary/images/favicon.png' %}">
<link rel="apple-touch-icon" sizes="152x152" href="{% static 'vocabulary/images/favicon.png' %}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'vocabulary/images/favicon.png' %}">
<link rel="icon" type="image/png" sizes="192x192"  href="{% static 'vocabulary/images/favicon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'vocabulary/images/favicon.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'vocabulary/images/favicon.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'vocabulary/images/favicon.png' %}">
<link rel="manifest" href="{% static 'vocabulary/manifest.json' %}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="{% static 'vocabulary/images/favicon.png' %}">
<meta name="theme-color" content="#ffffff">

dictionary/templates/vocabulary/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home | Dictionary{% endblock %}

{% block content %}
  <link rel="stylesheet" href="{% static 'vocabulary/css/wordsList.css' %}">
  <br>
  <br>
  {% if user.is_authenticated %}
    {% include './addWordForm.html' %} <!-- add word form -->
    <br>
    <br>

    <div id="words-list">
      {% if vocabulary_list %}
        {% for item in vocabulary_list %} <!-- words list -->
          {% include './wordCard.html' %} <!-- word card -->
        {% endfor %}
      {% else %}
        Add word!
      {% endif %}
    </div>
  {% else %}
    <p>Please, <strong>log in</strong> with google account to use the app!</p>
  {% endif %}
  <script src="{% static 'vocabulary/js/editHandler.js' %}"></script>
{% endblock %}

dictionary/templates/vocabulary/memorization.html
{% extends 'base.html' %}
{% block title %}Memorization | Dictionary{% endblock %}

{% block content %}
  <p>Coming soon, memorization!</p>
{% endblock %}

dictionary/templates/vocabulary/navigation.html
{% load socialaccount %}
{% load static %}

<link rel="stylesheet" href="{% static 'vocabulary/css/navigation.css' %}">

<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'vocabulary:home' %}">Vocabulary</a>
    <button class="navbar-toggler" onclick='menuToggle()' type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText"> <!-- show collapse collapsing -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a id="home" class="nav-link" aria-current="page" href="{% url 'vocabulary:home' %}">My words</a>
        </li>
        {% endif %}

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a id="memorization" class="nav-link" href="{% url 'vocabulary:memorization' %}">Memorization</a>
        </li>
        {% endif %}

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="/accounts/logout/">Log out</a>
        </li>
        {% endif %}

        {% if not user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% provider_login_url 'google' %}">Log in with google</a>
        </li>
        {% endif %}
      </ul>

      {% if user.is_authenticated %}
      <span class="navbar-text">
        Welcome, {{ request.user.email }}
      </span>
      {% endif %}
    </div>
  </div>
</nav>

<script src="{% static 'vocabulary/js/navigation.js' %}"></script>

dictionary/templates/vocabulary/wordCard.html
{% load static %}
<div class="word-item">
  <!-- show card state -->
  <div id="{{ item.id }}" class="word-item__show-state">
    <div>
      <strong class="word-element">{{ item.word }}</strong> : 
      <i class="word-element">{{ item.definition }}</i>
    </div>

    <div
      class="word-item__button-wrapper"
    >
      <input
        type="button"
        class="btn btn-success"
        style="margin-right: 10px;"
        name='edit'
        onclick='editHandler(event)'
        value="Edit"
      >
      <form action="{% url 'vocabulary:remove_word' item.id %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-default btn-danger">Delete</button>
      </form>
    </div>
    <input
      class="word-item__edit-button"
      type="image"
      src="{% static 'vocabulary/images/edit.svg' %}"
      onclick='editHandlerMobile(event)'
    />
  </div>

  <!-- start edit word card state block -->
  <div class="word-item__edit-state hide">
    <form
      action="{% url 'vocabulary:update_word' item.id %}"
      method="POST"
      class="word-item__edit-form">
      {% csrf_token %}
      <div class="form-row">
        <!-- word -->
        <div class="form-group col-md-6">
          <input
            type="text"
            class="form-control"
            autocomplete="off"
            required
            name="newWord"
            id="word"
            value="{{ item.word }}"
          >
        </div>

        <!-- definition -->
        <div class="form-group col-md-6">
          <input
            type="text"
            class="form-control"
            required
            name="newDefinition"
            autocomplete="off"
            id="definition"
            value="{{ item.definition }}"
          >
        </div>
        <div class="form-group col-md-6">
          <button
            type="submit"
            class="btn btn-success"
          >Update</button>
        </div>
      </div>
    </form>
  </div>
  <!-- end edit word card state block -->
</div>